services:
  service.exception_handler:
    class: ViachViach\ExceptionHandler\Service\ExceptionHandler
    public: false

  ViachViach\ExceptionHandler\Service\ExceptionHandler:
    alias: service.exception_handler
    public: true
