services:

  ViachViach\ExceptionHandler\Handler\ValidationExceptionHandler:
    class: ViachViach\ExceptionHandler\Handler\ValidationExceptionHandler
    arguments:
      - '@serializer'
      - '@ViachViach\ExceptionHandler\Handler\NotFoundHandler'
    public: public
    tags: [ exception.handler ]

  ViachViach\ExceptionHandler\Handler\NotFoundHandler:
    class: ViachViach\ExceptionHandler\Handler\NotFoundHandler
    arguments:
      - '@serializer'
      - '@ViachViach\ExceptionHandler\Handler\NormalizableHandler'
    public: false
    tags: [ exception.handler ]

  ViachViach\ExceptionHandler\Handler\NormalizableHandler:
    class: ViachViach\ExceptionHandler\Handler\NormalizableHandler
    arguments:
      - '@serializer'
      - '@ViachViach\ExceptionHandler\Handler\ExceptionHandler'
    public: false
    tags: [ exception.handler ]

  ViachViach\ExceptionHandler\Handler\ExceptionHandler:
    class: ViachViach\ExceptionHandler\Handler\ExceptionHandler
    arguments:
      - '@serializer'
    public: false
    tags: [ exception.handler ]

  ViachViach\ExceptionHandler\Service\ExceptionHandler:
    class: ViachViach\ExceptionHandler\Service\ExceptionHandler
    public: false

  ViachViach\ExceptionHandler\Service\ExceptionHandlerInterface:
    alias: ViachViach\ExceptionHandler\Service\ExceptionHandler
    public: true
