services:
  service.handler:
    class: ExceptionHandler\Service\Handler
    public: false

  service.exception_handler:
    class: ExceptionHandler\Service\ExceptionHandlerService
    arguments:
      - '@service.handler'
    public: false

  ExceptionHandler\Service\ExceptionHandlerInterface:
    alias: service.exception_handler
    public: true
